version: '3.4'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    build: 
        context: ./execute
        dockerfile: ./Dockerfile

  hangfire.api:
    image: ${DOCKER_REGISTRY-}hangfireapi
    build:
        context: .
        dockerfile: hangfire.api/Dockerfile
