version: '3.4'

services:
    mssql:
        container_name: banco        
        ports:
            - '1435:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Secret1234        
        volumes:
            - mssql_data:/var/opt/mssql
        networks:
              - local
        command:
          - /bin/bash
          - -c
          - |
            /opt/mssql/bin/sqlservr
            curl -s https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh | bash /dev/stdin localhost:1433
  

    hangfire.api:
        container_name: api
        restart: on-failure       
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:4001;http://+:5001
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - mssql    
        ports:
                - "4001:4001"   
                - "5001:5001"   
        networks:
                - local    

volumes:
  mssql_data:
    driver: local       

networks:
    local:
        driver: bridge      
