version: '3.4'

services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    build: 
            context: ./execute
            dockerfile: ./Dockerfile
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Secret1234
    volumes:
        - mssql_data:/var/opt/mssql
  

volumes:
  mssql_data:
    driver: local       